-- Esquema recomendado para el MVP (Supabase/PostgreSQL)
-- Usa identificadores simples e índices clave.

-- Perfiles de usuario (extensión de auth.users)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  avatar_url text,
  role text check (role in ('visitor','host','admin')) default 'visitor',
  created_at timestamptz default now()
);
create index if not exists profiles_role_idx on public.profiles(role);

-- Alojamientos (accommodations)
create table if not exists public.accommodations (
  id bigint generated by default as identity primary key,
  host_id uuid references public.profiles(id) on delete set null,
  title text not null,
  description text,
  price numeric(12,2) not null default 0,
  rating numeric(3,2) default 0,
  category text, -- ej: 'alojamiento', 'experiencia'
  location text, -- ej: barrio/ciudad
  image_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists accommodations_category_idx on public.accommodations(category);
create index if not exists accommodations_location_idx on public.accommodations(location);

-- Imágenes de alojamiento
create table if not exists public.accommodation_images (
  id bigint generated by default as identity primary key,
  accommodation_id bigint not null references public.accommodations(id) on delete cascade,
  url text not null,
  sort_order int default 0
);
create index if not exists accommodation_images_acc_idx on public.accommodation_images(accommodation_id);

-- Disponibilidad (slots por fecha)
create table if not exists public.availability (
  id bigint generated by default as identity primary key,
  accommodation_id bigint not null references public.accommodations(id) on delete cascade,
  date date not null,
  capacity int not null default 1,
  reserved int not null default 0,
  unique (accommodation_id, date)
);
create index if not exists availability_acc_date_idx on public.availability(accommodation_id, date);

-- Reservas
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  accommodation_id bigint not null references public.accommodations(id) on delete cascade,
  start_date date not null,
  end_date date not null,
  status text check (status in ('pending','confirmed','cancelled')) default 'pending',
  amount numeric(12,2) not null default 0,
  created_at timestamptz default now()
);
create index if not exists bookings_user_idx on public.bookings(user_id);
create index if not exists bookings_acc_idx on public.bookings(accommodation_id);

-- Mensajes entre usuarios/anfitriones
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  thread_id bigint,
  from_user uuid references public.profiles(id) on delete set null,
  to_user uuid references public.profiles(id) on delete set null,
  accommodation_id bigint references public.accommodations(id) on delete set null,
  text text not null,
  created_at timestamptz default now()
);
create index if not exists messages_thread_idx on public.messages(thread_id);

-- Reseñas
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  accommodation_id bigint not null references public.accommodations(id) on delete cascade,
  rating int check (rating between 1 and 5),
  comment text,
  created_at timestamptz default now(),
  unique (user_id, accommodation_id)
);
create index if not exists reviews_acc_idx on public.reviews(accommodation_id);

-- Categorías (opcional, normalización)
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  key text unique not null, -- ej: alojamiento, experiencia
  label text not null
);

-- Buenas prácticas adicionales:
-- - Políticas RLS: habilitar row level security y definir políticas por rol.
-- - Triggers para updated_at en accommodations.
-- - Constraints NOT NULL donde aplique según negocio.
-- - Índices adicionales para búsquedas (precio, rating) según uso.